language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t hoekstraja/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hoekstraja/docker-react npm run test